spring:
  application:
    name: eureka
  profiles: default

# If you want to store these settings in the config server prefixed with [spring, e.g. spring.cloud.config]
#  cloud:
#    config:
#      uri: http://localhost:8070

server:
  port: 8071

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enable-self-preservation: false

  instance:
    hostname: eurekahost


